#### TOBIG'S 15기 정규세션 4주차 SVM 
### ASSIGNMENT1. Multiclass SVM 구현

In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [37]:
scal = StandardScaler() #scaling
X = scal.fit_transform(X)

In [38]:
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [39]:
# One VS Rest 구현을 위해 1) class가 0 or not 2)class가 1 or not을 구분하기 위한 머신 등을 미리 만들어주자
svm_1 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_2 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_3 = SVC(kernel ='rbf', C = 5, gamma = 5)

In [40]:
from sklearn.model_selection import train_test_split #test/train 데이터로 분리
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [41]:
y_train = pd.get_dummies(y_train) #one hot encoding

In [42]:
y_train

setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [45]:
svm_1.fit(X_train,y_train.iloc[:,0]) # 데이터 클레스가 0 or not 구분해주는 머신
svm_2.fit(X_train,y_train.iloc[:,1]) # 데이터 클레스가 1 or not 구분해주는 머신
svm_3.fit(X_train,y_train.iloc[:,2]) # 데이터 클레스가 2 or not 구분해주는 머신
print(svm_1.predict(X_test)) #데이터 클래스가 0 or not을 구분해주는 애를 통해서 테스트 데이터의 클래스가 0인지, 0이 아닌인지 예측해보자

print(svm_1.decision_function(X_test)) #decision_function hyperplane과의 거리를 구하는 방법(필요하다면 활용해주세요!)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[-1.12470845 -0.86326953 -0.65281099 -0.50248821 -0.76284323 -0.87465573
  1.07709345 -0.99281647  0.47441336 -0.99842743 -0.83989348  0.15633457
  0.32871788 -0.97965464 -0.72385083 -0.92638376  1.28322481 -0.56240455
 -0.72719892 -0.99509775  0.43166724 -0.96451557 -0.82991366 -1.03020581
 -0.75166835  1.13461335  0.39943974 -1.04194106 -0.93376548 -1.06133798]


In [46]:
# 부호가 모든 같은 경우가 있는가? > 모두 동점인 경우가 생길 것
for i in range(len(X_test)):
    # ~. decision_function을 이용하면 해당 데이터가 하이퍼플레인으로부터 얼마나 떨어져있는지 '거리'가 나온다!
    # 다음은 그 값의 부호를 이용해 모두가 동점인 경우가 있는지 출력하는 함수 
    if (np.sign(svm_1.decision_function(X_test)[i]) == np.sign(svm_2.decision_function(X_test)[i]))\
    and (np.sign(svm_2.decision_function(X_test)[i]) == np.sign(svm_3.decision_function(X_test)[i])):
        print(i)

3
17
18


In [44]:
## Case 1 : One vs Rest SVM을 이부분에 구현해주세요 위 결과들을 이용해서 multi class SVM을 직접 구현해주세요! 하드코딩이 하시기 편할겁니다.


In [26]:
result1 = svm_1.decision_function(X_test)   #setosa
result2 = svm_2.decision_function(X_test)   #versicolor
result3 = svm_3.decision_function(X_test)   #virginica

In [27]:
result1

array([-1.12470845, -0.86326953, -0.65281099, -0.50248821, -0.76284323,
       -0.87465573,  1.07709345, -0.99281647,  0.47441336, -0.99842743,
       -0.83989348,  0.15633457,  0.32871788, -0.97965464, -0.72385083,
       -0.92638376,  1.28322481, -0.56240455, -0.72719892, -0.99509775,
        0.43166724, -0.96451557, -0.82991366, -1.03020581, -0.75166835,
        1.13461335,  0.39943974, -1.04194106, -0.93376548, -1.06133798])

In [28]:
result2

array([ 1.36054602,  0.62859488,  0.0580828 , -0.36987093, -0.25686625,
       -0.79229874, -1.03195247, -0.87132049, -0.77957234,  0.99327762,
       -0.73309581, -0.64607768, -0.71843897, -0.80882458,  0.47748663,
        0.69953462, -1.11879121, -0.1870504 , -0.24458236, -0.99337352,
       -0.76149141, -0.96812018,  0.11310267,  1.06892719, -0.56749692,
       -1.05639624, -0.74817515, -1.0537858 , -0.89721836,  1.17126024])

In [29]:
result3

array([-1.26277651, -0.77964936, -0.40539105, -0.13070947,  0.02643314,
        0.57365649, -1.04443118,  0.88027844, -0.69605517, -0.99074328,
        0.52442024, -0.51171892, -0.61157919,  0.78148257, -0.75517707,
       -0.76905925, -1.16380018, -0.25333938, -0.0251979 ,  0.98843144,
       -0.67129528,  0.89577306, -0.30363489, -1.03647008,  0.31622662,
       -1.07758405, -0.65251719,  1.09632055,  0.85541707, -1.11042784])

In [30]:
result = [] #결과값 저장할 list
for i in range(X_test.shape[0]):
    if result1[i]==max(result1[i], result2[i], result3[i]):
        result.append('setosa')
    elif result2[i]==max(result1[i], result2[i], result3[i]):
        result.append('versicolor')
    elif result3[i]==max(result1[i], result2[i], result3[i]):
        result.append('virginica')

In [31]:
result

['versicolor',
 'versicolor',
 'versicolor',
 'virginica',
 'virginica',
 'virginica',
 'setosa',
 'virginica',
 'setosa',
 'versicolor',
 'virginica',
 'setosa',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'setosa',
 'versicolor',
 'virginica',
 'virginica',
 'setosa',
 'virginica',
 'versicolor',
 'versicolor',
 'virginica',
 'setosa',
 'setosa',
 'virginica',
 'virginica',
 'versicolor']

In [47]:
from sklearn.metrics import accuracy_score
print("accuracy: ",accuracy_score(y_test, result))

accuracy:  0.8666666666666667


In [ ]:
# Case 2 : One vs One SVM을 이 부분에 구현해주세요. (선택사항)


['versicolor', 'versicolor', 'versicolor', 'virginica', 'virginica', 'virginica', 'setosa', 'virginica', 'setosa', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'versicolor', 'versicolor', 'setosa', 'versicolor', 'virginica', 'virginica', 'setosa', 'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa', 'setosa', 'virginica', 'virginica', 'versicolor']


0.8666666666666667

In [49]:
# 원래 라이브러리가 제공하는 multi class SVM과 여러분이 구현한 multiclass SVM 결과를 비교해주세요
from sklearn.model_selection import train_test_split #데이터셋 분리
from sklearn import metrics
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(X, y, test_size=0.2, random_state=48)

svm_4 = SVC(kernel ='rbf', C = 5, gamma = 5)
svm_4.fit(X_train_2, y_train_2)
y_pred = svm_4.predict(X_test_2)

metrics.accuracy_score(y_test_2,y_pred)

0.8333333333333334