# Assignment1 

## Matrix 구현 
1. Linear Regression 에서 쓰이는 **정규방정식**을 행렬로 구현하고, sklearn 혹은 OLS 패키지를 통해 구한 **실제 값과 비교**해 주세요 
2. LSE에서 쓰이는 Loss Function, **MSE**를 행렬로 구현해 출력해 주세요 

### Data Load 

In [1]:
import pandas as pd 
data = pd.read_csv("assignment1.csv")

In [2]:
data.head()

y    x1    x2  x3   x4    x5
0  10  38.9  64.7   4  868  59.7
1  13  41.6  45.3  -4  957  61.4
2  11  39.7  74.1   8  786  61.0
3   7  37.3  48.0  19  984  67.5
4  10  39.5  51.9   6  700  57.2

In [3]:
data.shape # y:(9,1), X:(9,5)

(9, 6)

In [4]:
X = data.drop(["y"], axis=1)
y = data.y

In [5]:
# matrix 계산을 위해 numpy 형태로 바꾸어 줍니다 
X = X.to_numpy()
y = y.to_numpy()

In [6]:
X

array([[  38.9,   64.7,    4. ,  868. ,   59.7],
       [  41.6,   45.3,   -4. ,  957. ,   61.4],
       [  39.7,   74.1,    8. ,  786. ,   61. ],
       [  37.3,   48. ,   19. ,  984. ,   67.5],
       [  39.5,   51.9,    6. ,  700. ,   57.2],
       [  37.4,   53.6,   -5. , 1037. ,   58.8],
       [  35.1,   71.4,    3. ,  986. ,   58.6],
       [  38.8,   58.3,    6. ,  819. ,   59.2],
       [  36.6,   52.6,  -19. ,  791. ,   54.4]])

In [7]:
y

array([10, 13, 11,  7, 10,  9,  9,  6,  5], dtype=int64)

### 1. Normal Equation

In [8]:
import numpy as np
from numpy.linalg import inv 

In [10]:
def estimate_beta(X, y):
    designX = np.insert(X, 0, 1., axis=1)
    beta_hat = np.dot(np.dot(inv(np.dot(np.transpose(designX), designX)), np.transpose(designX)), y)
    # dot(dot(inv(dot(trans(X),X)), trans(X)), y)
    
    return beta_hat

In [11]:
beta_hat = estimate_beta(X, y)
beta_hat

array([-3.92447368e+01,  1.31232583e+00,  8.53744361e-02,  7.41849897e-02,
        1.50018573e-02, -3.42273652e-01])

#### 실제 값과 비교

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model = LinearRegression()
model.fit(X, y)

pred = model.predict(X)

In [14]:
print(model.intercept_) # intercept
print(model.coef_) # 추정된 회귀계수 (intercept제외)

-39.24473678135658
[ 1.31232583  0.08537444  0.07418499  0.01500186 -0.34227365]


### 2. MSE

In [15]:
def MSE(X, y, beta_hat):
    designX = np.insert(X, 0, 1., axis=1)
    y_pred = np.dot(designX, beta_hat)
    mse = np.sum(np.square(y- y_pred))/(len(y)-len(beta_hat))
    
    return mse

In [16]:
MSE(X, y, estimate_beta(X, y))

4.846793168705752

### 3.MLE

#### 바구니 안에 파란구슬과 빨간구슬이 들어있을 때, 10개를 추출하여보니 파란구슬이 2개 빨간구슬이 8개가 추출되었습니다. 
#### 이때 바구니안에는 파란구슬과 빨간구슬이 각각 몇개있는지에 대해서 최대우도추정법을 이용해 논리적으로 설명해주세요. 
- 수식은 있어도 좋고 말로 풀어쓰셔도 좋습니다
- 추출은 복원추출을 전제로 합니다
- 글자수 제한은 없습니다. 많이 쓰라는 얘기가 아니라 정말 제한이 없습니다. 너무 부담가지고 쓰지마세요.

최대우도추정법은 "likelihood" 즉 어떤 값이 관측되었을 대, 이것이 어떤 확률분포에서 왔을지에 대한 가능성을 기반으로 한다. 이에 의하면 바구니 안에서 구슬을 10번 추출했을 시 8개의 빨간 구슬과 2개의 파란 구슬이 나왔다는 것은 해당 사건의 발생확률이 높다는 것을 의미하며, 해당 사건의 확률을 최대로 하는 상황(바구니 구슬 색 분포)을 추정한다. 

파란 구슬이 추출될 확률을 p 라 할 때, 위와 같이 2개의 파란 구슬, 8개의 빨간 구슬이 나온 확률은 P(B B R R R R R R R R | p)=p^2*(1-p)^8 이다. 이러한 모든 사건들은 10C2*p^2*(1-p)^8 로 나타낼 수 있다. 이때 이를 로그 취하면 log(10C2) + 2logp + 8log(1-p) 가 되고, 이를 p에 대해 미분하면 2/p-8/(1-p) 이다. 미분식이 0이 되게 하는 p 값이 최대값이므로 2/p-8/(1-p)=0 이 되는 p의 값은 2이다. 

따라서 최대우도추정법의 정의에 따라 주어진 사건의 확률을 최대로 하는 p의 값은 2가 되고, 바구니 안에는 10개 중에 2개가 파란 구슬이라고 볼 수 있다. 